### ISSUE TITLE
Responsive Login/Register Page

### ISSUE THREAD

**Issue by FR33MAN9808** [PhucMaii/BookNook#44]
Login Page:
- Icon should outlined
- Responsive page
- Link login and signup pages
- Password text field need to be password type
Sign Up Page:

- Text field color change
- Icon at the beginning of select

**Comment by inigomari** [comment]
changed the icon to outlined, linked the login and signup pages, changed the password type fields to password fields, changed text field colors, then added the icons at the beginning of select
